if RUBY_PLATFORM =~ /java/
  # -*- ruby -*-
  require 'rake/javaextensiontask'
  
  Rake::JavaExtensionTask.new('nn') do |ext|
    ext.name = 'nn'
    ext.debug = true
    ext.lib_dir = 'library/nn'
    ext.source_version='1.7'
    ext.target_version='1.7'
  end
end

desc 'clean'
task :clean do
  FileUtils.rm_rf(FileList['tmp', 'library'])
end

desc 'run'
task :run do
  sh `rp5 run xor.rb`
end
