#!/usr/bin/env ruby

# This is a utility to export Ruby-Processing
# sketches to applets that can be viewed online.
# -- omygawshkenas

require File.join(File.dirname(__FILE__), "base_exporter.rb")

module Processing
  class AppletExporter < BaseExporter
    def export!

      # Check to make sure that the main file exists
      @main_file_path, main_file = *get_main_file()
      unless @main_file_path && File.exists?(@main_file_path)
        puts <<-USAGE
        
      The applet generator will generate a web-ready applet for you.
      Usage: script/applet <path_to_sketch>
      Example: script/applet samples/jwishy.rb 
      
      USAGE
        exit
      end
      
      # Extract all the cool details.
      source_code, class_name, title, width, height, description, libs_to_load = *extract_information()
      
      # Make the appropriate directory
      applet_dir = "applets/#{main_file.sub(".rb", "")}"
      remove_entry_secure applet_dir if File.exists?(applet_dir)
      mkdir_p applet_dir
      
      # Copy over all the required files
      necessary_files = [@main_file_path, "ruby-processing.rb", "core.jar"]
      necessary_files << "data" if File.exists?("data")
      necessary_files += Dir.glob("script/applet_files/{*,**}") # Exporter files
      necessary_files += Dir.glob("library/{#{libs_to_load.join(",")}}") if libs_to_load.length > 0
      cp_r(necessary_files, applet_dir)
      
      # Figure out OpenGL replacements, if necessary:
      @starting_class = @opengl ? "com.sun.opengl.util.JOGLAppletLauncher" : "org.jruby.JRubyApplet"
      if @opengl
        opengl_files = Dir.glob(applet_dir + "/opengl/*.jar")
        opengl_files += Dir.glob(applet_dir + "/opengl/library/*.jar")
        move(opengl_files, applet_dir)
        remove_entry_secure(applet_dir + "/opengl")
        necessary_files.map! {|file| file.match(/^opengl/) ? File.basename(file) : file }
      end
      
      
      # Figure out the substitutions to make.
      file_list = Dir.glob(applet_dir + "{/**/*.{rb,jar},/data/*.*}").map {|f| f.sub(applet_dir+"/","")}
      h1 = title ? "<h1>#{title[1]}</h1>" : ""
      description = description ? "<div id='description'>" + h1 + "<p>" + description[1].gsub!("\n #", "") + "</p></div>" : ""
      @title = title ? title[1] : "Ruby-Processing Sketch"
      @width = width ? width[1] : "400"
      @width_plus_14 = (@width.to_i + 14).to_s
      @height = height ? height[1] : "400"
      @main_file = main_file
      @file_list = file_list.join(",")
      @description = description
      
      # Fill in the blanks in the HTML.    
      final_index = File.new(applet_dir+"/index.html.erb")  
      rendered_index = ERB.new(final_index.read, nil, "<>", "rendered_index").result(binding)
      File.open(applet_dir + "/index.html", "w") do |file|
        file.print rendered_index
      end
      rm(applet_dir + "/index.html.erb")
      
    end
  end
end

Processing::AppletExporter.new.export!

