#!/bin/bash

# This script opens up Ruby-Processing Sketches in a Live-Coding
# Environment (jIRB), so that you can go code on the fly.

if [ -e "$1" ]
then
  mac=`which appletalk`
  if [ -n "$mac" ]
  then
    java -cp script/base_files/jruby-complete.jar -Xdock:name=Ruby-Processing -Xdock:icon=script/application_files/Contents/Resources/sketch.icns org.jruby.Main script/live_files/live_coding.rb "$1"
  else
    java -cp script/base_files/jruby-complete.jar org.jruby.Main script/live_files/live_coding.rb "$1"
  fi
else
  mac=`which appletalk`
  if [ -n "$mac" ]
  then
    java -cp script/base_files/jruby-complete.jar -Xdock:name=Ruby-Processing -Xdock:icon=script/application_files/Contents/Resources/sketch.icns org.jruby.Main script/live_files/live_coding.rb
  else
    java -cp script/base_files/jruby-complete.jar org.jruby.Main script/live_files/live_coding.rb
  fi  
fi