#!/bin/bash

# This script lets you open up Ruby-Processing sketches
# without having to install JRuby.

if [ -e "$1" ]
then
  java -cp script/base_files/jruby-complete.jar org.jruby.Main "$1"
else
  echo "Couldn't find that sketch."
  echo "Usage: script/open path/to/my_sketch.rb"
  exit
fi