#!/bin/bash

# Here's the script to run the specs. It's a sketchy way to go.

JRUBY=`which jruby`
JRUBY=`ruby -e "puts File.dirname(File.dirname('$JRUBY'))"`

if [ -e "$JRUBY" ]
then
  java -cp jruby-complete.jar -Djruby.lib=$JRUBY/lib -Djruby.home=$JRUBY org.jruby.Main $JRUBY/bin/spec $* -f s
else
  echo "You'll need to have a real JRuby install to run the specs."
  exit
fi