#!/bin/bash

# This script opens up Ruby-Processing Sketches and observes their source,
# reloading the sketch every time you save a change.

if [ -e "$1" ]
then
  mac=`which appletalk`
  if [ -n "$mac" ]
  then
    java -cp script/base_files/jruby-complete.jar -Xdock:name=Ruby-Processing -Xdock:icon=script/application_files/Contents/Resources/sketch.icns org.jruby.Main script/watch_files/watch.rb "$1"
  else
    java -cp script/base_files/jruby-complete.jar org.jruby.Main script/watch_files/watch.rb "$1"
  fi
else
  echo "Couldn't find that sketch."
  echo "Usage: script/watch path/to/my_sketch.rb"
  exit
fi